-- Leak reports table: periodic aggregated leak analysis per user.
-- Generated by weekly job, consumed by weekly push reports and LLM tools.

CREATE TABLE leak_reports (
  id BIGSERIAL PRIMARY KEY,
  chat_id BIGINT NOT NULL REFERENCES users(user_id),
  report_period TEXT NOT NULL,            -- "2026-W13", "2026-03"
  spot_category TEXT NOT NULL,
  sample_count INT NOT NULL,
  deviation_rate REAL NOT NULL,           -- fraction (0-1) of hands where hero deviated
  avg_ev_loss REAL,                       -- average estimated EV loss per deviation (bb)
  total_ev_loss REAL,                     -- total estimated EV loss (bb)
  trend TEXT,                             -- "improving", "stable", "worsening"
  trend_delta REAL,                       -- change in deviation_rate vs prior period
  gto_wizard_drill_url TEXT,              -- direct link to relevant drill
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(chat_id, report_period, spot_category)
);

CREATE INDEX idx_leak_reports_chat ON leak_reports(chat_id, report_period);

-- Enable RLS (app uses direct postgres connection, bypasses RLS)
ALTER TABLE leak_reports ENABLE ROW LEVEL SECURITY;
